#!/usr/bin/env bash
set -eu

folder=$(readlink -f $1)
cd `dirname $0`

files=(
$(ls $(cat clone.files | sed "s/#.*//; /^\s*$/d"))
)

[[ ! -d $folder ]] && mkdir -p $folder || {
  echo $folder exists
  exit 1
}

for f in ${files[@]}; do
  dirnames=$(dirname $f)
  mkdir -p ${folder}/${dirnames}
  cp -v $f $folder/${dirnames}
done
